services:
  db:
    image: postgres:18-trixie
    container_name: postgres-db
    restart: always
    ports:
      - 5432:5432
    shm_size: 128mb
    volumes:
      - ./postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: Sup3rSecret0
    networks:
      - default

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    restart: unless-stopped
    environment:
      DATA_SOURCE_URI: postgresql://postgres:Sup3rSecret0@db/game_db?sslmode=disable
      DATA_SOURCE_USER: postgres
      DATA_SOURCE_PASS: Sup3rSecret0
    depends_on:
      - db

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8090:8080
    networks:
      - default
    depends_on:
      - db

  grafana:
    image: grafana/grafana:main
    container_name: grafana
    depends_on:
      - db
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    restart: unless-stopped
    networks:
      - default

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: prometheus
    restart: unless-stopped
    networks:
      - default
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=7d"

  vllm:
    image: vllm/vllm-openai:latest
    container_name: vllm_service
    ports:
      - "9000:9000"
    environment:
      - VLLM_HOST=0.0.0.0
      - VLLM_PORT=8000
      - HUGGING_FACE_HUB_TOKEN=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
    command: [
      "--model", "Qwen/Qwen2.5-1.5B-Instruct",
      "--host", "0.0.0.0",
      "--port", "9000",
      "--dtype", "auto",
      "--api-key", "EMPTY",
      "--gpu-memory-utilization", "0.8",
      "--disable-log-stats",
      "--trust-remote-code",
      "--enforce-eager",
      "--api-key", "EMPTY"
    ]


    networks:
      - default
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    depends_on:
      - db
    ports:
      - 5678:5678
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_HOST: db
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_USER: postgres
      DB_POSTGRESDB_PASSWORD: Sup3rSecret0




volumes:
    postgres-data:
    prometheus-data:
    grafana-data:
    n8n_data:
networks:
  default:
    name: uno-network