services:
  server:
    image: uno-server:1
    container_name: uno-server
    ports:
      - 8081:8080
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - default
    depends_on:
      - db

  client1:
    build:
      context: .
      dockerfile: deployment/Dockerfile.client
    image: uno-client:latest
    container_name: uno-client-1
    env_file:
      - .env
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=8080
      - CLIENT_NAME=client1
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - default

  client2:
    build:
      context: .
      dockerfile: deployment/Dockerfile.client
    image: uno-client:latest
    container_name: uno-client-2
    env_file:
      - .env
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=8080
      - CLIENT_NAME=client2
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - default

  db:
    image: postgres:18-trixie
    container_name: postgres-db
    restart: always
#    ports:
#      - 5432:5432
    shm_size: 128mb
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: Sup3rSecret0
    networks:
      - default

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - default

networks:
  default:
    name: uno-network