FROM python:3.12-slim
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential gcc libpq-dev libpq5 ca-certificates python3-dev\
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt
COPY src/game.py /app/
COPY src/logger.py /app/
COPY src/config.py /app/
COPY src/server.py /app/
COPY src/analytics.py /app/
COPY src/utils.py /app/

EXPOSE 8000

CMD ["python3", "server.py"]